'use client';

import { useState, useEffect } from 'react';
import Head from 'next/head';
import MapGL from '../../components/map';
import Image from 'next/image';
import logo from '../../public/one-accord.webp';
import { CountdownTimer } from '@/components/countDownTimer/index';

export default function Home() {
  const [currentTime, setCurrentTime] = useState('');

  useEffect(() => {
    // Función para obtener la hora actual y formatearla
    const getTime = () => {
      const date = new Date();
      let hours = date.getHours();
      const ampm = hours >= 12 ? 'PM' : 'AM';
      hours = hours % 12 || 12;
      const minutes = date.getMinutes();
      setCurrentTime(`${hours}:${minutes < 10 ? '0' : ''}${minutes} ${ampm}`);
    };

    // Llamar a la función inicialmente y luego cada minuto para actualizar la hora
    getTime();
    const interval = setInterval(getTime, 60000); // Actualizar cada minuto

    return () => clearInterval(interval); // Limpiar el intervalo cuando el componente se desmonte
  }, []);

  return (
    <>
      <div>
        <Head>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
          <title>One Accord</title>
        </Head>
        <main className='w-screen h-screen relative overflow-hidden flex flex-col'>
          <section className='flex-grow p-0 m-0'>
            <MapGL />
          </section>

          <div className='absolute top-0 left-0 pt-5 pl-5'>
            <Image
              src={logo}
              alt='logo'
              priority={true}
              sizes='(min-width: 60em) 24vw, (min-width: 28em) 45vw, 100vw'
              className='object-contain cursor-pointer'
            />
          </div>

          <div className='absolute top-0 right-0 z-10 pt-5 pr-5 flex flex-col text-white'>
            <h2 className='text-4xl font-bold pb-5'>ACTION TIMER</h2>
            <div className='border border-white rounded-lg p-4'>
              <p className='text-center text-4xl font-bold'>{currentTime}</p>
            </div>
          </div>

          <section className='w-screen h-10vh overflow-hidden'>
            {/* Timer Component */}
            <CountdownTimer />
          </section>

          <section className='w-screen h-50vh'>{/* Feed Component */}</section>
        </main>
      </div>
    </>
  );
}
